# Copie para /etc/pve-postinstall.conf no host Proxmox
PVE_MODE="standalone"
TIMEZONE="America/Sao_Paulo"
DEBIAN_CODENAME="trixie"

# Cluster (opcional): veja etc/pve-postinstall.cluster.conf.example
